### ISSUE TITLE
[Crash] When using the Tangle Binder on the server side and moving the mouse over any block that is bound to a specific dimension can cause the game to crash.

### ISSUE THREAD

**Issue by xiaojing911** [SuperMartijn642/Entangled1.12#83] opened 2024-06-16 03:05 UTC
Version Info

Minecraft,1.12.2
Entangled,1.3.18a
Server::Forge

Steps to Reproduce

1.Login to the server.
2.Enter the dimensions you have created
3. Use the Entangled Binder to bind any block within the dimension.
4. Upon opening the inventory and hovering the mouse over the Entangled Binder that has been bound within the dimension, the game crashes.

Crash repor
[crash-2024-06-16_10.46.01-client.txt](https://github.com/user-attachments/files/15856020/crash-2024-06-16_10.46.01-client.txt)
t

**Comment by SuperMartijn642** [comment] 2024-06-18 15:17
This seems to be a duplicate of #82.

**Closed as completed by SuperMartijn642** 2024-06-18 15:17 UTC
Labels: duplicate, crash
