### ISSUE TITLE
[Bug] Bound entangled blocks cannot be placed

### ISSUE THREAD

**Issue by Lightcx** [SuperMartijn642/Entangled1.12#75] opened 2024-03-23 11:34 UTC
**Version Info**
- Minecraft, Forge 1.20.1
- Entangled, Entangled-1.3.17-forge-mc1.20
- modpack sky greg 1.22 https://www.curseforge.com/minecraft/modpacks/sky-greg

**Description of the Bug**
Bound entangled blocks cannot be placed. Even the bound block and the entangled block are both in overworld.
Tooltip message: Binder is bound to a unknown dimension "minecraft:"

**Steps to Reproduce**
1.place a entangled block
2.bind it to any block
3.break the bound entangled block
4.try to place the block down and encounter the bug

**Screenshots**
![image](https://github.com/SuperMartijn642/Entangled/assets/74954277/537611c1-3527-4a4f-ad66-a61c484e31df)

**Comment by SuperMartijn642** [comment] 2024-03-23 12:05
Duplicate of #71.

**Closed as completed by SuperMartijn642** 2024-03-23 12:05 UTC
Labels: bug
