### ISSUE TITLE
[Crash] Rendering entangled integrated dynamics cable/component

### ISSUE THREAD

**Issue by weszhuang** [SuperMartijn642/Entangled1.12#34] opened 2021-11-27 04:59 UTC
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.9-mc1.16
- IntegratedDynamics-1.16.5-1.10.4
- IntegratedTunnels-1.16.5-1.8.7

**Steps to Reproduce**

1. entangle a integrated dynamics cable or component(e.g. interfaces, exporters, importers) 
2. and get within range to render the entangled block

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Entangled/files/7611233/latest.log)

**Comment by SuperMartijn642** [comment] 2021-11-29 01:04
This seems to be caused by Integrated Dynamics. I have submitted a pull request to them to fix the issue https://github.com/CyclopsMC/IntegratedDynamics/pull/1114.

**Comment by weszhuang** [comment] 2021-11-29 04:38
Also as a note for future issues relating to rendering issues in other mods being revealed by entangled there is a to be implemented feature to blacklist rendering certain entangled target blocks.
[Entangled Issue link](https://github.com/SuperMartijn642/Entangled/issues/35)

**Comment by SuperMartijn642** [comment] 2021-11-30 15:53
The pull request has been merged, so it should be fixed in newer versions of Integrated Dynamics.

**Closed as completed by SuperMartijn642** 2021-11-30 15:53 UTC
Labels: crash
