### ISSUE TITLE
 [Crash] Moving the mouse over any block bound to certain dimensions using the Entangled Binder causes the game to crash. 

### ISSUE THREAD

**Issue by xiaojing911** [SuperMartijn642/Entangled1.12#79] opened 2024-04-20 13:46 UTC
Version Info

Minecraft,1.12.2
Entangled,1.3.18
Steps to Reproduce
1.Enter the dimensions you have created
2. Use the Entangled Binder to bind any block within the dimension.
3. Upon opening the inventory and hovering the mouse over the Entangled Binder that has been bound within the dimension, the game crashes.

Screenshots:
Custom Dimensions:https://streamable.com/qdlrlq

Crash report
[crash-2024-04-20_21.11.02-client.txt](https://github.com/SuperMartijn642/Entangled/files/15048380/crash-2024-04-20_21.11.02-client.txt)

Additionally, I used Just Enough Dimensions to create my own custom dimension. Here is the code for my custom dimension.
{
  "config_version": {
    "id": "__default",
    "version": 0
  },
  "dimensions": [
    {
      "dim": 119,
      "normal_biomes": true,
      "dimensiontype": {
        "id": 119,
        "name": "Void World",
        "suffix": "Void World",
        "keeploaded": true,
        "worldprovider": "WorldProviderSurfaceJED"
      },
        "worldinfo_onetime":{
          "generatorName": "flat",
          "generatorOptions": "3;minecraft:bedrock,53*minecraft:stone,4*minecraft:dirt,minecraft:grass,minecraft:air;decoration",
          "DayTime": 6000,
          "GameRules": {
          "doDaylightCycle": "false"
          }
        }
    }
  ]
}

**Comment by SuperMartijn642** [comment] 2024-04-20 14:03
Isn't this just a duplicate of your own issue which I closed yesterday 🤔
Why report the same issue again #76

**Comment by xiaojing911** [comment] 2024-04-20 14:21
Because the latest version of the mod, upon entering my custom dimension for testing in the game, still caused a crash.

**Comment by xiaojing911** [comment] 2024-04-20 14:21
> 这不就是我昨天🤔关闭的您自己问题的重复吗 为什么要再次报告相同的问题#76

Because the latest version of the mod, upon entering my custom dimension for testing in the game, still caused a crash.

**Comment by SuperMartijn642** [comment] 2024-04-20 14:29
Are you using version 1.3.17 or 1.3.18? Because you put 1.3.17 in the issue, but 1.3.18 is the latest.

**Comment by xiaojing911** [comment] 2024-04-20 14:32
I'm sorry, the version number was incorrect in the question, but the game test was conducted using the latest version.

**Comment by xiaojing911** [comment] 2024-04-20 14:32
> 您使用的是 1.3.17 还是 1.3.18 版本？因为您在问题中输入了 1.3.17，但 1.3.18 是最新的。

I'm sorry, the version number was incorrect in the question, but the game test was conducted using the latest version.

**Comment by SuperMartijn642** [comment] 2024-04-22 18:31
Seems I fixed it for the entangled block tooltip, not the entangled binder tooltip, whoops...
Should work for both now in version 1.3.18a for Minecraft 1.12.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-04-22 18:31 UTC
Labels: crash
