### ISSUE TITLE
[Bug] smth goes wrong when using entangled block cross-dimensionally

### ISSUE THREAD

**Issue by YiRanMushroom** [SuperMartijn642/Entangled1.12#54] opened 2023-02-14 16:17 UTC
**Version Info**
- Minecraft, 1.12.2
- Entangled, Entangled 1.3.12

**Description of the Bug**
Entangled can sometimes work incorrectly when using it cross-dimensionally

**Steps to Reproduce**
If entangle a drawer controller in the overworld and use it in other dimensions, some thing could not recognize the Entangled block as an invalid container(eg. random things item collector), not the same as when using it in the same dimension, which would run correctly.

And when using it cross-dimensionally, some item could not be import in it, while others can. (When in a same dimension, all the thing can be transfered correctly)

**Screenshots**
...

**Comment by SuperMartijn642** [comment] 2023-02-14 16:21
This may be caused by the drawer controller being unloaded. Entangled doesn't do anything when the area of the bound block becomes unloaded.

Is the area with the drawer controller chunk loaded? If not, could you see if keeping the area loaded makes it work?

**Comment by YiRanMushroom** [comment] 2023-02-14 16:27
I used ftb chunk loading, so I think it has already been loaded.

**Comment by YiRanMushroom** [comment] 2023-02-14 16:33
It works generally, but can't work totally, As I mentioned. but I think that the second problem may because of same item was detected in the same drawer system(because I fixed it by removing the same item). However, if it was used in the same dimension, all the problem seems not to be occuring.

**Comment by YiRanMushroom** [comment] 2023-02-14 16:40
In the over world, a random things item collector can be placed on an entangled block (entangled to a drawer controller).
![image](https://user-images.githubusercontent.com/114495322/218800094-75b92713-20cf-42f0-a15d-5ab914cdd74e.png)
But can't be placed on if the entangled block is in another dimention (entangled to the same drawer controller).
![image](https://user-images.githubusercontent.com/114495322/218800865-e2dee8e6-5269-45d6-9a6a-998bc2cfb4e5.png)

**Comment by SuperMartijn642** [comment] 2023-08-01 11:59
This has likely been fixed in one of the newer versions of Entangled as I cannot reproduce the issue.
If the issue persists please let me know, for now I'll close the issue.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2023-08-01 11:59 UTC
Labels: bug
