### ISSUE TITLE
[Crash] [1.21] Entangled latest version crash with neoforge

### ISSUE THREAD

**Issue by Periam** [SuperMartijn642/Entangled1.12#87] opened 2024-07-20 22:38 UTC
**Version Info**
- Minecraft, Neoforge 21.0.113
- Entangled, entangled-1.3.18-neoforge-mc1.12

**Steps to Reproduce**
1 Install Entangled and all depencies
2 launch game

**Crash report (~/logs/latest.log)**
![image](https://github.com/user-attachments/assets/38ccbb67-7a79-4436-a76c-594e53e26605)

[debug.log](https://github.com/user-attachments/files/16322519/debug.log)
[latest.log](https://github.com/user-attachments/files/16322520/latest.log)

**Comment by SuperMartijn642** [comment] 2024-07-20 23:35
Seems this was caused by changes in NeoForge 21.0.102.
Should be fixed now in my core library version 1.1.17a for 1.21 NeoForge.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-07-20 23:35 UTC
Labels: crash
